on: [push]
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "A" > note.txt
      - uses: actions/upload-artifact@v7
        with:
          name: note.txt
          archive: false
      - run: cat note.txt
  two:
    needs: one
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: note.txt
      - run: cat note.txt
